### ISSUE TITLE
CompilerExtension

### ISSUE THREAD

**Issue by castamir** [Joseki/LeanMapper-extension#1]
create a CompilerExtension that will solve the following:
- create LeanMapper\Connection
- create Mapper (default or custom)
- enable profiler with more accurate paths to files (and lines) -> fire event within findBy method

**Comment by rebendajirijr** [comment]
@castamir What's the recommended way for registration of filters (including registration using custom `Nette\DI\CompilerExtension`)?

**Comment by castamir** [comment]
Nevím Jirko, já filtry nepoužívám... btw nejsi z Ústí? :D

**Comment by castamir** [comment]
Filters are no longer supported in this extension. I reccommend you to use `findBy*` methods  with Query objects and call it from entity itself (see [Entity](https://github.com/Joseki/LeanMapper-extension/blob/master/src/Joseki/LeanMapper/Entity.php#L15))
