### ISSUE TITLE
Missing Mapper constructor

### ISSUE THREAD

**Issue by rebendajirijr** [Joseki/LeanMapper-extension#3]
I'm having following problem after installation:
`Nette\DI\ServiceCreationException` service leanMapper.mapper: Unable to pass arguments, class `Joseki\LeanMapper\Mapper` has no constructor.

I'm using Nette 2.3@dev.

**Comment by castamir** [comment]
I was not able to replicate your error only by myself. Could you write down what exactly you did, please? (content of your config file(s) etc.)

Quickly tested Nette v2.3.3 (stable) using my [sandbox](https://github.com/Joseki/Sandbox)

**Comment by rebendajirijr** [comment]
@castamir I think it's caused by [this service definition](https://github.com/Joseki/LeanMapper-extension/blob/master/src/Joseki/LeanMapper/DI/Extension.php#L50), two arguments are passed, but no constructor is defined in the Mapper class. I've only registered the extension in neon and set up database connection parameters.

**Comment by castamir** [comment]
@rebendajirijr of course, this DI extension requires [PackageMapper](https://github.com/Joseki/LeanMapper-extension/blob/master/src/Joseki/LeanMapper/PackageMapper.php)
But you don't need this DI extension at all. This DI extension is a new way, how to avoid writing repository definitions in config.neon and how to allow custom namespaces for these repositories.

See 
[config file](https://github.com/Joseki/Sandbox/blob/master/app/config/extension.LeanMapper.neon#L15)
[concrete PackageMapper](https://github.com/Joseki/Sandbox/blob/master/app/MyApplication/LeanMapper/Mapper.php)

[MyApplication/Navigation/SectionRepository](https://github.com/Joseki/Sandbox/blob/master/app/MyApplication/Navigation/SectionRepository.php)
[MyApplication/Auth/UserRepository](https://github.com/Joseki/Sandbox/blob/master/app/MyApplication/Auth/UserRepository.php)

**Comment by castamir** [comment]
Perhaps [mapper class definition](https://github.com/Joseki/LeanMapper-extension/blob/master/src/Joseki/LeanMapper/DI/Extension.php#L12) should be defined as PackageMapper.

**Comment by rebendajirijr** [comment]
@castamir I think the default mapper class should be `Joseki\LeanMapper\PackageMapper` then :)

**Comment by castamir** [comment]
fixed in a402af9
